### ISSUE TITLE
알카노이드 게임 플레이 도중 발생하는 에러 현상

### ISSUE THREAD

**Issue by JaeGyu** [izeye/pilot#130]
1. 총알 아이템 적용 시  총알을 발사하기위해 마우스 버튼을 연속으로 클릭하면
   볼이 클릭에 반응하여 스스로 가야 할 방향으로 진행하지 못하고 위아래로 왔다갔다하는
   현상이 발생함
2. 스테이지 클리어후 다음 판으로 넘어가면 시작하기도 전에 게임오버가 되어 있는 경우가 
   있음

**Comment by izeye** [comment]
1번은 총알과 타일 충돌 시에도 볼의 방향을 바꾸도록 되어 있어 발생한 문제이고,

2번은 스테이지 클리어 후 공의 방향을 초기화하지 않아서 발생한 문제입니다.

모두 해결되었습니다.
