### ISSUE TITLE
Bootstrap 추가 후 텍스트 필드 내 텍스트 하단이 짤리는 문제.

### ISSUE THREAD

**Issue by izeye** [izeye/pilot#70]
Bootstrap 추가 후 텍스트 필드 내 텍스트 하단이 짤리는 문제가 있습니다.

**Comment by JaeGyu** [comment]
해결 했습니다.

**Comment by izeye** [comment]
오.. Mac Google Chrome은 잘되네요 ㅎㅎ

Mac Firefox는 Message Label이 Text Input에 가려지네요 ;;
