### ISSUE TITLE
슬롯머신 페이지에서 Pilot 서비스 메뉴가 동작 안함.

### ISSUE THREAD

**Issue by izeye** [izeye/pilot#80]
슬롯머신 페이지에서 Pilot 서비스 메뉴가 동작 안합니다.

Bootstrap은 jQuery latest (1.8.2)에서 잘 동작하는데

Slot Machine 앱이 의존하는 jQuery 플러그인은 jQuery 1.6.1 기반으로 되어 있어서 서로 충돌납니다.

**Comment by JaeGyu** [comment]
해결 했습니다.

**Comment by JaeGyu** [comment]
bootstrap.js 안에 145번째줄이 에러가 나는거 같아요. $(document).on() <- on함수가 검색해보니 jquery 1.7이상에서 지원이 되나봐요. 슬롯머신보다 bootstrap가 밑에 나오면 슬롯머신의 1.6버전때문에 $(document).on() 에서의 on함수를 찾을 수 없다고 나오는거 같아요. jquery 버전 충돌로인한 문제 같아요.
bootstrap.js 가 밑에 선언 되어져 있을경우 요소검사의 console을 켜놓고 슬롯머신 메뉴를 클릭하면 에러가 발생해요.
