### ISSUE TITLE
HTML 서비스 동작하도록 복구

### ISSUE THREAD

**Issue by izeye** [izeye/pilot#97]
HTML 서비스 동작하도록 복구합니다.

**Comment by JaeGyu** [comment]
WEB.xml 파일에 정의된 서블릿 매핑에서 Dispatcher Servlet설정부분의 URL패턴이 기존 *.do에서 /로 변경되어
있었습니다. 모든 요청을 DispatcherServlet가 받게 되어 있어서 기존에 되던 html이나 jsp 의 요청이 처리가 안되고 있었습니다. 
*.do방식이 아닌 / 방식을 유지한 상태에서 html이나 jsp나 그림파일 요청(jpg,png,bmp)을 하기위해선 다른 서블릿으로 분리해서 관리를 해야 할 것 같습니다. 
우선 *.do를 살려 두었습니다.
